<?php

namespace Hospice\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function findAllBetweenStartAndRepeatingEndDate($start, $repeatingEnd)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT e, r from HospiceSiteBundle:Event e
                LEFT JOIN e.recurOptions r WHERE e.start<=:end 
                AND ((r.id IS NULL and e.end>=:start) OR (r.end IS NULL or r.end<:end))')
            ->setParameter('start', $start)
            ->setParameter('end', $repeatingEnd)
        ;
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
